name: Linux Release

on:
    workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
  ARTIFACT:     DLCreator.AppImage

jobs:
  build:
    permissions: write-all
    runs-on:  ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 15
        platform: x64

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.1'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      ${{ env.QT_VERSION }}
        host:         linux
        target:       desktop
        arch:         linux_gcc_64
        dir:          ${{ runner.temp }}
        setup-python: false

    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Configure project
      run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=clang -DCMAKE_CXX_COMPILER:FILEPATH=clang++ -S${{ env.SOURCE_DIR }} -B${{ env.SOURCE_DIR }}/build/linux -G Ninja

    - name: Build project
      run: cmake --build ${{ env.SOURCE_DIR }}/build/linux --config Release --target all --

    - name: Deploy
      run: | 
        wget https://github.com/probonopd/linuxdeployqt/releases/latest/download/linuxdeployqt-continuous-x86_64.AppImage && 
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage &&
        mv linuxdeployqt-continuous-x86_64.AppImage linuxdeployqt.AppImage &&
        ./linuxdeployqt.AppImage ${{ env.SOURCE_DIR }}/build/linux/DLCreator -always-overwrite

    - name: Zip
      run: 7z a -tzip -mx5 -r0 ${{ env.SOURCE_DIR }}/build/DLCreator-linux.zip ${{ env.SOURCE_DIR }}/build/linux

    - name: Create release
      uses: actions/create-release@v1
      id: new-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1
        release_name: Test
        draft: true
        prerelease: true

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.new-release.outputs.upload_url }}
        asset_path: ${{ env.SOURCE_DIR }}/build/DLCreator-linux.zip
        # asset_path: DLCreator.AppImage
        asset_name: DLCreator.zip
        asset_content_type: application/zip