name: Linux Release

on:
    workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
  ARTIFACT:     DLCreator.AppImage

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 15
        platform: x64

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.1'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      ${{ env.QT_VERSION }}
        host:         linux
        target:       desktop
        arch:         linux_gcc_64
        dir:          ${{ runner.temp }}
        setup-python: false

    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=clang -DCMAKE_CXX_COMPILER:FILEPATH=clang++ -S${{ env.SOURCE_DIR }} -B${{ env.SOURCE_DIR }}/build -G Ninja

    - name: AppImage
      working-directory: ${{ env.SOURCE_DIR }}/build
      run: |
        wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x deploy.AppImage
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/Qt/5.15.2/gcc_64/lib/
        cp ${{ env.SOURCE_DIR }}/linux/* .
        ./deploy.AppImage planets-qml.desktop -appimage -no-translations -qmldir=${{ env.SOURCE_DIR }} -extra-plugins=renderers
        mv Qt_planets_app*.AppImage ${{ env.ARTIFACT }}  