name: Linux Release

on:
    workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
  ARTIFACT:     qt-planets-linux-build.AppImage

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 18.1.1
        platform: x64

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.1'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      ${{ env.QT_VERSION }}
        host:         linux
        target:       desktop
        arch:         linux_gcc_64
        dir:          ${{ runner.temp }}
        setup-python: false

    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      run:  cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=clang -DCMAKE_CXX_COMPILER:FILEPATH=clang++ -S${{ env.SOURCE_DIR }} -B${{ env.SOURCE_DIR }}/build -G Ninja