name: Windows Release

on:
    workflow_dispatch:

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
  ARTIFACT:     qt-planets-build.zip

jobs:
  build:
    permissions: write-all
    runs-on:  windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64
    
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
    
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.1'
    
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          setup-python: false
              